config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "welcome#index"

  resources :items, only: [:index, :show]
  resources :reviews, except: [:show, :edit, :update]

end

app/models/item.rb
class Item < ActiveRecord::Base
has_many :reviews

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :item

  validates :title, :star, :review, presence: :true
  validates :star, inclusion: 1..5

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
        :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController



def index
  @item = Item.all
end

def show
  @item = Item.find(params[:id])
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @review = Review.all
  end

  def new
    @item = Item.find(params[:item_id])
    @review = @item.reviews.new
  end

  def create
    @item = Item.find(params[:review][:item_id])
    @review = @item.reviews.new(safe_review_params)
    if @review.save()
      redirect_to @item
    else
      render 'new'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @item = @review.item_id
    @review.destroy

    redirect_to items_path
  end

  private

  def safe_review_params
    params.require(:review).permit(:title, :star, :review)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
  
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_review.html.erb
<div class="thumbnail">
  <div class="caption">
    <p><strong><%= review.title %></strong></p>
    <p>
      <% review.star.times do %>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
      <% end %>
      <% (5 - review.star).times do %>
        <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
      <% end %>
    </p>
    <p><%= review.review %></p>
    <% if current_user %>
    <%= link_to "Delete this Review", review, method: 'delete' %>
    <%end%>
  </div>
</div>

app/views/items/index.html.erb
<h1>All Items</h1>

<div class="row">
  <% @item.each do |item| %>
    <div class="col-md-4">
      <div class="thumbnail img-thumbnail item-thumbnail">
        <%= image_tag item.image, class: "img-rounded" %>
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= link_to "View This Item", item_path(item), class: "btn btn-primary", role: "button" %></p>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= image_tag @item.image, class: "img-responsive img-rounded" %>
  </div>
  <div class="col-md-7">
    <h1><%= @item.name %></h1>
    <h2><%= number_to_currency(@item.price) %></h2>
    <p>
      <%= link_to "Buy This Item", "mailto:duran.beverly@gmail.com?subject=#{@item.name}", class: "btn btn-primary btn-lg", role: "button" %>
      <%= link_to "Write a Review", new_review_path(item_id: @item.id), class: "btn btn-lg", role: "button" %>
    </p>
    <% @item.reviews.each do |review|%>
      <%= render partial: "review", locals: {review: review} %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtGallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><%= link_to "BD", root_path, class: "navbar-brand" %></li>
        <li><%= link_to "Items", items_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div>
  </nav>
  <div class="container">
    <% if notice || alert %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Create a Review</h1>

    <%= form_for @review, html: {multipart: true} do |f| %>
      <div class="form-group">
        <%= f.hidden_field :item_id, value: @item.id %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :review %>
          <%= f.text_area :review, class: "form-control", rows: "3" %>
        </div>
        <div class="form-group">
          <%= f.label :star %>
          <%= f.number_field :star, class: "form-control" %>
        </div>
        <%= f.submit "Submit Review", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Hello, art nerds!</h1>
  <p>My name is Beverly, and this is my online store for clay figurines.</p>
  <p><%= link_to "Shop Now", items_path, class: "btn btn-primary btn-lg", role: "button" %></p>
</div>